### ISSUE TITLE
On Fedora 27, the script doesn't identify the kernel-rt

### ISSUE THREAD

**Issue by ycollet** [raboof/realtimeconfigquickscan#11]
I use Fedora 27 64 bits with a realt time kernel.
The realTimeConfig script doesn't idenfity the kernel-rf:

Kernel with Real-Time Preemption... not found - not good
Kernel without real-time capabilities found

Here is the content of the config file:
<code>
$ grep CONFIG_PREEMPT /boot/config-4.14.6-300.rt7.2.fc27.ccrma.x86_64+rt 
CONFIG_PREEMPT_RCU=y
CONFIG_PREEMPT_NOTIFIERS=y
CONFIG_PREEMPT=y
CONFIG_PREEMPT_RT_BASE=y
CONFIG_PREEMPT_LAZY=y
# CONFIG_PREEMPT_NONE is not set
# CONFIG_PREEMPT_VOLUNTARY is not set
# CONFIG_PREEMPT__LL is not set
# CONFIG_PREEMPT_RTB is not set
CONFIG_PREEMPT_RT_FULL=y
CONFIG_PREEMPT_COUNT=y
# CONFIG_PREEMPT_TRACER is not set
</code>
CONFIG_PREEMPT_RT doesn't exist anymore, and an CONFIG_PREEMPT_RT_BASE seems to have replaced this flag.

**Comment by raboof** [comment]
Thanks for getting in touch. I wonder if it even still makes sense to check for this configuration, as lots of the -rt patch set has been merged into mainline already and kernel performance has improved dramatically even without the (remaining) RT patches.

What do you think?

**Comment by ycollet** [comment]
I will try to test ASAP (tonight) if I can reach the same performances with a standard kernel for music.

I think the best is to leave the test and try to fix it. Some people will still want to install and test a kernel rt for their activities ...
I will try to propose a fix for tonight ...


----- Mail original -----
De: "Arnout Engelen" <notifications@github.com>
À: "raboof/realtimeconfigquickscan" <realtimeconfigquickscan@noreply.github.com>
Cc: "ycollet" <ycollette.nospam@free.fr>, "Author" <author@noreply.github.com>
Envoyé: Lundi 8 Janvier 2018 12:16:29
Objet: Re: [raboof/realtimeconfigquickscan] On Fedora 27, the script doesn't identify the kernel-rt (#11)



Thanks for getting in touch. I wonder if it even still makes sense to check for this configuration, as lots of the -rt patch set has been merged into mainline already and kernel performance has improved dramatically even without the (remaining) RT patches. 

What do you think?

**Comment by ycollet** [comment]
I performed some tests with the version from the git repo and it works fine.
The package shipped by fedora is quite old ...
<code>
Nom          : realTimeConfigQuickScan
Version      : 0
Révision     : 0.19.20120506hg.fc26
Architecture : noarch
Taille       : 71 k
Source       : realTimeConfigQuickScan-0-0.19.20120506hg.fc26.src.rpm
Dépôt        : @System
Depuis le dé : fedora
Résumé       : Inspect realtime system settings URL          : http://code.google.com/p/realtimeconfigquickscan/
Licence      : GPLv2+
Description  : Inspects system settings, and makes suggestions for improving realtime/audio
              : performance.
</code>

**Comment by raboof** [comment]
This project has been rewritten and moved to https://codeberg.org/rtcqs/ - I'll close this issue here, updating the fedora package should be tracked in the fedora project :)
