### ISSUE TITLE
Rationale for max_user_watches

### ISSUE THREAD

**Issue by ghost** [raboof/realtimeconfigquickscan#12]
The script outputs:

```
Checking checking sysctl inotify max_user_watches... < 524288 - not good
increase max_user_watches by adding 'fs.inotify.max_user_watches = 524288' to /etc/sysctl.conf and rebooting
For more information, see http://wiki.linuxaudio.org/wiki/system_configuration#sysctlconf
```

However, the mentioned link contains:
> There are references on the net on adjusting the fs.inotify.max_user_watches value also for enhanced performance. But it remains very unclear where these references come from and if adjusting this value actually does anything at all. The max_user_watches parameter sets the maximum number of files your system can monitor with inotify (which is part of the kernel) for changes. Setting this parameter too low results in inotify failing. Setting it too high can make inotify needlessly consume memory. Best is to not touch the default settings as setting this parameter is unrelated to performance in an audio context.

I suggest we make it consistent. Probably one of these:
* the wiki should be edited to explain the magic number
* the script should explain the magic number
* since current wiki edition discourages touching inotify settings, remove the check from the script or make it optional

**Comment by light2yellow** [comment]
As a follow-up, this is what [ArchWiki](https://wiki.archlinux.org/index.php/Professional_audio) says:

> Then, there is inotify which watches for changes to files and reports them to applications requesting this information. When working with lots of audio data, a lot of watches will need to be kept track of, so they will need to be increased.

So, you might want to reference the link above in the script.

**Comment by raboof** [comment]
This project has been rewritten and moved to https://codeberg.org/rtcqs/ - I'll close this issue here, you're still welcome to apply the discussed improvements :)
