### ISSUE TITLE
If username contains 'audio', the check for an audio group will report multiple groups

### ISSUE THREAD

**Issue by mxa** [raboof/realtimeconfigquickscan#13]
realtimeconfigquickscan complains about multiple groups named _audio_

```
Checking for multiple 'audio' groups... yes - not good
Found 9 groups with name 'audio'. You should not have duplicate 'audio' groups.
For more information, see http://wiki.linuxaudio.org/wiki/system_configuration#audio_group
```
`cat /etc/group` will reveal that there is in fact only one group with the name _audio_. The username however contains the string _audio_ which apparently gets picked up by the script.

**Comment by mxa** [comment]
ok hold on

**Comment by mxa** [comment]
https://github.com/raboof/realtimeconfigquickscan/pull/14

**Comment by raboof** [comment]
Thanks!
