### ISSUE TITLE
Sound Card IRQ

### ISSUE THREAD

**Issue by mxa** [raboof/realtimeconfigquickscan#17]
Maybe add a little example or hint on how to do this in the readme?

** Set $SOUND_CARD_IRQ to the IRQ of your soundcard to enable more checks.
   Find your sound card's IRQ by looking at '/proc/interrupts' and lspci.

**Comment by mxa** [comment]
This is a support request. Can you show with an example where and how to set this variable for an external usb sound card?

**Comment by mxa** [comment]
**Step one: Finding the IRQ:**
looking at `/proc/interrupts `
```
 16:         25          0         37          0          0          0          8          0   IO-APIC  16-fasteoi   ehci_hcd:usb1
 23:         48          0          0         34          0          0          0          0   IO-APIC  23-fasteoi   ehci_hcd:usb2
```
looking at `lsusb ` i suspect it's this line:
`Bus 003 Device 066: ID 22f0:0014  ` (there is no name on this line for the Allen&Heath ZEDi8)

So it's either 16 or 23?

**Step two: Setting local variable**
`SOUND_CARD_IRQ=16`
(Found @ https://www.tecmint.com/set-unset-environment-variables-in-linux/)

**Result:**
Still asks to set the variable.

**Comment by raboof** [comment]
perhaps you need `export SOUND_CARD_IRQ=16`? Make sure to do it in the same terminal you're using to invoke realtimeconfigquickscan

**Comment by mxa** [comment]
ah, adding `export` does something: it removes the message to set the variable. There is no extra output though.

**Comment by raboof** [comment]
From https://github.com/raboof/realtimeconfigquickscan/blob/8e112a6d9e514eabfd4f98e19a5f760ba7d6092a/realTimeConfigQuickScan.pl#L78 it looks like it does warn when there are other devices sharing the sound card IRQ, but no 'good' message when none such device is found.

Would you be interested in contributing that as an improveent?

**Comment by mxa** [comment]
made a PR to explain in the README how to set the variable https://github.com/chairaudio/realtimeconfigquickscan/pull/1

**Comment by raboof** [comment]
The change looks good, but you made it a PR against your own repo. Could you make it a PR against my repo instead?

**Comment by mxa** [comment]
arg... done

**Comment by mxa** [comment]
> Would you be interested in contributing that as an improvement?

I might if i find the time. Will close this issue though as it is out of the scope of this issue.
