### ISSUE TITLE
Neither script seems to work: no output

### ISSUE THREAD

**Issue by lucmp** [raboof/realtimeconfigquickscan#21]
How long are those two scanning scripts supposed to take to do their job?

When I run '**perl -I ./QuickScan.pl**' or '**perl -I ./realTimeConfigQuickScan.pl**' they just seem to hang for about five minutes, when I finally give up and ^c kill them.

There are no error messages. They won't even finish and return. They just seem to hang.

**Comment by abrock** [comment]
> 'perl -I ./QuickScan.pl'

Try this (note the two ./):
`perl -I ./ ./QuickScan.pl`

The parameter `-I ./` tells perl to look for modules in the current directory, your command told perl to look for modules in the directory "QuickScan.pl".

**Comment by raboof** [comment]
@abrock found a nice way to no longer require the `-I ./` part in #23 :+1:
