### ISSUE TITLE
cpufreq-set hint may be outdated

### ISSUE THREAD

**Issue by jose1711** [raboof/realtimeconfigquickscan#25]
there's no `cpufreq-set` on my arch linux system, the name of the binary is `cpufreq-selector`. executable comes with `gnome-applets 3.30.0-1`.

**Comment by raboof** [comment]
Good info! Would you be interested in creating a PR that improves the message?

**Comment by jose1711** [comment]
it would not be an issue. however it would be useful to know if `cpufreq-set` still exists in the rest of commonly used distributions. can you check on your system?

**Comment by raboof** [comment]
Yes, it's still part of `cpufrequtils` on Debian. `cpufreq-selector` is also available, but under `gnome-applets`. Since not everyone would have the latter, I think it'd make sense to mention both.

**Comment by jose1711** [comment]
did some homework and found out that `cpufrequtils` is considered deprecated (debian still packages it but project homepage is gone). `cpupower` is a suggested replacement and `cpufreq-selector` from `gnome-applets` only depends on it. it therefore makes more sense to show `cpupower` command instead of `gnome-applet`'s `cpufreq-selector`.

**Comment by jose1711** [comment]
fixed via 2d87395
