### ISSUE TITLE
IRQ for USB sound cards

### ISSUE THREAD

**Issue by NolanSyKinsley** [raboof/realtimeconfigquickscan#28]
Is it possibly to set an IRQ for a USB sound card? Even when the sound card is the only device on the USB controller it says either nothing, or that there are multiple devices on the IRQ. I have an M-Audio Transit, and hyperx cloud 2 headphones as my only audio devices and am trying to track down an issue with only OBS crackling, hoping your tool might shed some light somewhere.

**Comment by raboof** [comment]
I'm not sure I quite understand, you might have more luck at the forum at linuxmusicians.com  ?

**Comment by NolanSyKinsley** [comment]
When I run this tool, at the end of the output it says "** Set $SOUND_CARD_IRQ to the IRQ of your soundcard to enable more checks.", but I am using a USB sound card, or USB headphones which act as a USB sound card. These do not have an IRQ as it uses the IRQ of the USB controller it is on. When I give that IRQ, it either has no more output, or states that there are multiple devices at that IRQ. Is there a way to pass something like the "sysfs.path = "/devices/pci0000:00/0000:00:13.0/usb7/7-3/7-3:1.0/sound/card2"" instead of the IRQ to point to the specific PCI device?


I am trying to get as much information on my sound system to fix some audio issues when everything I can currently check everybody says should be fine with no issues, and nothing is throwing any errors. I don't even really know what more information your tool can provide me, I am just trying to scrape every bit of information up as I can.

**Comment by raboof** [comment]
> These do not have an IRQ as it uses the IRQ of the USB controller it is on

I think it makes sense to check if there are no other devices on the IRC the USB controller is on. Many machines have several USB controllers, and moving your USB sound card (/headphones) to a the hub that doesn't share an IRQ with a 'heavy' device might be helpful.

> When I give that IRQ, it either has no more output, or states that there are multiple devices at that IRQ

Perhaps when it does not find any other devices at that IRQ is should emit a `- good` message then?

> Is there a way to pass something like the "sysfs.path = "/devices/pci0000:00/0000:00:13.0/usb7/7-3/7-3:1.0/sound/card2"" instead of the IRQ to point to the specific PCI device?

Not currently. How would that help?

**Comment by mxa** [comment]
Came here with the same question.
My crappy Lenovo laptop has 4 USB buses, but only bus 3 is actually accessible through a physical USB port, the other ones are either not in use or used by internal components.

```
$ cat /proc/interrupts    
  0: IO-APIC   2-edge      timer
  1:  IO-APIC   1-edge      i8042
  8: IO-APIC   8-edge      rtc0
  9: IO-APIC   9-fasteoi   acpi
 12: IO-APIC  12-edge      i8042
 16: IO-APIC  16-fasteoi   ehci_hcd:usb1
 18: IO-APIC  18-fasteoi   i801_smbus
 23: IO-APIC  23-fasteoi   ehci_hcd:usb2
 29: PCI-MSI 327680-edge      xhci_hcd
 30: PCI-MSI 1572864-edge      rtsx_pci
 31: PCI-MSI 2097152-edge      enp4s0
 32: PCI-MSI 512000-edge      ahci[0000:00:1f.2]
 33: PCI-MSI 32768-edge      i915
 34: PCI-MSI 360448-edge      mei_me
 35: PCI-MSI 524288-edge      nvidia
 36: PCI-MSI 2621440-edge      iwlwifi
 37: PCI-MSI 49152-edge      snd_hda_intel:card0
 38: PCI-MSI 442368-edge      snd_hda_intel:card1
```
```

$ lsusb
Bus 002 Device 002: ID 8087:8000 Intel Corp. 
Bus 002 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 001 Device 002: ID 8087:8008 Intel Corp. 
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 004 Device 004: ID 17ef:304f Lenovo 
Bus 004 Device 003: ID 2109:0812 VIA Labs, Inc. VL812 Hub
Bus 004 Device 002: ID 2109:0812 VIA Labs, Inc. VL812 Hub
Bus 004 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 003 Device 002: ID 8087:07dc Intel Corp. 
Bus 003 Device 018: ID 2c2f:0003 Sensel Sensel Morph
Bus 003 Device 016: ID 046d:c03e Logitech, Inc. Premium Optical Wheel Mouse (M-BT58)
Bus 003 Device 009: ID 145f:019f Trust 
Bus 003 Device 012: ID 046a:b090 Cherry GmbH Keyboard
Bus 003 Device 013: ID 0424:4060 Standard Microsystems Corp. Ultra Fast Media Reader
Bus 003 Device 010: ID 0424:2640 Standard Microsystems Corp. USB 2.0 Hub
Bus 003 Device 007: ID 0424:2514 Standard Microsystems Corp. USB 2.0 Hub
Bus 003 Device 006: ID 1a40:0101 Terminus Technology Inc. Hub
Bus 003 Device 015: ID 17ef:304e Lenovo OneLink Pro Dock       
Bus 003 Device 014: ID 0bc2:2322 Seagate RSS LLC SRD0NF1 Expansion Portable (STEA)
Bus 003 Device 011: ID 22f0:0014  
Bus 003 Device 008: ID 2109:2812 VIA Labs, Inc. VL812 Hub
Bus 003 Device 005: ID 2109:2812 VIA Labs, Inc. VL812 Hub
Bus 003 Device 004: ID 0bda:5719 Realtek Semiconductor Corp. Integrated Camera
Bus 003 Device 003: ID 138a:0011 Validity Sensors, Inc. VFS5011 Fingerprint Reader
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```

**Comment by raboof** [comment]
This project has been rewritten and moved to https://codeberg.org/rtcqs/rtcqs - I'll close this issue here
