### ISSUE TITLE
Feature request: check for threadirqs kernel option if no rt kernel is found

### ISSUE THREAD

**Issue by mxa** [raboof/realtimeconfigquickscan#31]
## Procedure:
Run the check for the rt-kernel. If it was found, **good**, go to next check.
If not found check for threadirqs option `grep threadirqs /proc/cmdline` if found, **good**. if not found: **not good**, neither rt-kernel nor kernel with threadirqs option loaded.

## Reasoning:
real-time kernels are not any more (since kernel 2.6.39!) necessary to achieve real-time performance. an alternative is the threadirqs enabled kernel with the rtirq script.
Currently realtimeconfigquickscan is only accepting a rt-kernel as a valid configuration.

**Comment by mxa** [comment]
example output of grep threadirqs /proc/cmdline 

```
$ grep threadirqs /proc/cmdline 
BOOT_IMAGE=/boot/vmlinuz-5.3.18-050318-lowlatency root=UUID=fffc9ae4-c288-40f1-b008-0b03347c3cb8 ro threadirqs quiet splash vt.handoff=7

```

**Comment by raboof** [comment]
Sounds good to me! Perhaps still 'mention' rt kernels but not so strongly anymore. Would you be interested in PR'ing?

**Comment by mxa** [comment]
I can give it a try, but it will take some time.

**Comment by mxa** [comment]
Chris Caudle is adding this caveat on the LAU list:

> With the caveat that you will also need to check whether the kernel is
> running the full RT patch, in which case IRQ handling is always threaded,
> so the threadirqs command line option is not needed.  Also note that even
> with the threadirqs command line, I do not think threaded IRQ handling is
> implemented if the PREEMPT option is not selected when the kernel is
> compiled.  That was the case in the past, I have not verified it is still
> the case with the very latest, although if you are looking for low latency
> you will probably want to verify that the kernel is configured with at
> least PREEMPT if not using the full PREEMPT-RT patches.
