### ISSUE TITLE
feature request: installation script

### ISSUE THREAD

**Issue by magnetophon** [raboof/realtimeconfigquickscan#37]
It would be great if you could add an installation script so that distros do not need to write code like this:

https://src.fedoraproject.org/rpms/realTimeConfigQuickScan/blob/30c2ded31bfa26cd861d67fc32379484c1e1d58a/f/realTimeConfigQuickScan.spec#_43

https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=realtimeconfigquickscan-git&id=e9339a57f0e79ebb3526a5aae73040a11acea9fa#n25

https://github.com/NixOS/nixpkgs/blob/f2e529a167c75ebe53d21db5b9a27caeb66b5af7/pkgs/applications/audio/real_time_config_quick_scan/default.nix#L23

It could be a simple makefile or maybe one of the things suggested in https://perlmaven.com/makefile-pl-of-module-install

**Comment by raboof** [comment]
Agreed. I'm not planning on looking into this myself, but definitely a PR introducing a Makefile would be welcome!

**Comment by raboof** [comment]
This project has been rewritten and moved to https://codeberg.org/rtcqs/rtcqs - I'll close this issue here
