### ISSUE TITLE
Check also if Swap is active before testing the swappiness: SwappinessCheck.pm.

### ISSUE THREAD

**Issue by jujudusud** [raboof/realtimeconfigquickscan#39]
Hi here,
My Archlinux is running without swap.

Is it possible to check if swap is active before running the swappiness test ?

I'm thinking about a test with this command:
`$ swapon --show`
Thanks.

**Comment by raboof** [comment]
That sounds good! Would you be interested in creating a PR?

**Comment by jujudusud** [comment]
Yes, I will be proud to contribute.
Do you want me to contribute directly or to fork ?
Can I comment on Linux musicians thread to Ask for users there vues on the better way to code that ?

Don't know how to code thé loop with non return value.
I will check that as soon as possible ... It's ok for me though

**Comment by raboof** [comment]
> Do you want me to contribute directly or to fork ?

I like the fork/PR workflow

> Can I comment on Linux musicians thread to Ask for users there vues on the better way to code that ?

Sure, you can also ask questions here

**Comment by jujudusud** [comment]
Ok, come on guys! :-)
The problem is that, even if you 'swapoff' your system like me, the vm.swappiness parameter already exists and is set (to 60 or anything else you want) but, is not used. And the check is not "correct".
I think we have to check if swap is used before checking the value. We have to use a new if, then, else but, I don't know to write it, to code it in perl.

So:

- The code must check if swap is in use with something like "$ swapon --show"
- If the result is blank (null) the swap is not in use, just tell it with a message and go to end
- if the result is not blank, then parse like it is today.

As you can see I'm not familiar with the language.

How can I code the swapon check and see and analyse the result ?

**Comment by raboof** [comment]
> I think we have to check if swap is used before checking the value

Makes sense to me!

> How can I code the swapon check and see and analyse the result ?

You can probably use backticks (or qx) to run the command and collect its output (https://perlmaven.com/qx), then use a regex to check whether it is empty? LMK if you'd like more help ;)

**Comment by raboof** [comment]
Thanks!
