### ISSUE TITLE
Hz1000Check.pm not really needed anymore

### ISSUE THREAD

**Issue by Gimmeapill** [raboof/realtimeconfigquickscan#4]
It looks like the timer config doesn't make much of a difference anymore on recent kernels (I'd say at least since the 4.x series).

The setting has been dropped from the Arch RT kernel (unofficial):
https://aur.archlinux.org/packages/linux-rt/

And this seems to be confirmed empirically by more than one user:
https://www.linuxmusicians.com/viewtopic.php?f=27&t=15210&p=68236#p68236

Maybe the sript should be updated in this regard?

**Comment by raboof** [comment]
So did this option disappear completely? or should I check for either 1000hz or  `CONFIG_HIGH_RES_TIMERS=y` ?

**Comment by Gimmeapill** [comment]
The option is still there, but enabling it hardly seem to make any difference for real time audio. This is however quite recent - I'd say 1-2 years max.
So if you can check for either, but also check for the kernel version, that would probably make a more sensible diagnostic.

**Comment by raboof** [comment]
It would indeed be nice to have some way of benchmarking these kinds of things, so we can check their impact over time/versions/configurations

**Comment by Gimmeapill** [comment]
Update: I got some hints from the Arch linux-rt maintainer in the thread below: 
https://aur.archlinux.org/pkgbase/linux-rt/#news
So it looks like only CONFIG_HIGH_RES_TIMERS=y is needed
