### ISSUE TITLE
Feature request: some optional tests/ benchmarks

### ISSUE THREAD

**Issue by Gimmeapill** [raboof/realtimeconfigquickscan#5]
What about moving beyond simple configuration checking and running some workload simulations from the RT tests suite (if present on the system)? I'm thinking in particular about cyclictest: https://rt.wiki.kernel.org/index.php/Cyclictest.
This would provide some actual performance data that could be useful for troubleshooting / fine tuning..

**Comment by raboof** [comment]
I agree this would be really useful.

Probably should be a separate tool though?
