### ISSUE TITLE
RtPrioCheck,chrt

### ISSUE THREAD

**Issue by 7W33D** [raboof/realtimeconfigquickscan#6]
Hi raboof,
When I run quickscan on some of my machines (Arch) everything is fine.
On others (Stretch & AvLinux2016) i get  can't chrt 80 error.
All systems have correct /etc/limits.d/audio.conf.
I did notice on my Arch system I can manually run "chrt 80 echo success" with success.
but on others I get "failed to set set pid 0's policy: Invalid request "
If I run chrt -r or chrt -f its fine.  chrt man says default is -r but also says default
linux policy is -o.  my thought is that "-f" is the one we're actually concerned with(?).
(eg. jackd's realtime thread is SCHED_FIFO)
I edited the chrt entry in my RtPrioCheck to be "chrt -f 80 echo success" and it now works on
all systems.
Is this correct/incorrect? Am I missing something?
Anyway, thanks for your help and for providing such a useful tool!!
tweed

**Comment by raboof** [comment]
Seem accurate, updated! Thanks for the report!
