### ISSUE TITLE
failed on Debian Sid

### ISSUE THREAD

**Issue by lrfinotti** [raboof/realtimeconfigquickscan#8]
I cannot run the script in up to date Debian Sid.

```
$ perl ./realTimeConfigQuickScan.pl
Can't locate QuickScanEngine.pm in @INC (you may need to install the QuickScanEngine module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.24.1 /usr/local/share/perl/5.24.1 /usr/lib/x86_64-linux-gnu/perl5/5.24 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.24 /usr/share/perl/5.24 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at ./realTimeConfigQuickScan.pl line 21.
BEGIN failed--compilation aborted at ./realTimeConfigQuickScan.pl line 21.
```

QuickScanEngine.pm is in the same directory:

```
$ ls
AudioGroupCheck.pm  GovernorCheck.pm       KernelConfigCheck.pm  PreemptRtCheck.pm   realTimeConfigQuickScan.pl*  SwappinessCheck.pm
BackgroundCheck.pm  HighResTimersCheck.pm  MultiAudioCheck.pm    QuickScanEngine.pm  RootCheck.pm                 SysCtlCheck.pm
Check.pm            HpetCheck.pm           NoAtimeCheck.pm       QuickScan.pl*       RtcCheck.pm                  WatchesCheck.pm
COPYING             Hz1000Check.pm         NoHzCheck.pm          README.md           RtprioCheck.pm
```

Any idea what is wrong?

**Comment by lrfinotti** [comment]
After some digging, I've found out that I needed to add the current directory to @INC (where perl looks for modules).  This could be done with the option -I (capital "i", no lowercase "l") of perl:
```
$ perl -I ./ ./realTimeConfigQuickScan.pl
```

Could I suggest you add this to the README?  

I will close this anyway.  Sorry about the "noise" and thanks for the _very_ useful script!

**Comment by raboof** [comment]
Hmm, reopening because this is at *least* a 'documentation bug' :)

Thanks for reporting, I'm not sure when I'd have time to dig into this, but a PR is always welcome :)

**Comment by u-ilyas** [comment]
@lrfinotti, try to set PERL5LIB in bash. ```export PERL5LIB=/home/foobar/code``` works for me.

**Comment by CrocoDuckoDucks** [comment]
Hi there!

The same issue happens now on Arch: see [here](https://aur.archlinux.org/packages/realtimeconfigquickscan-git/#news).

These lines should be able to add the current directory to @INC regardless of main script location:
```perl
use FindBin;
use lib $FindBin::Bin;
```
Dropping them into realTImeConfigQuickScan.pl just before `use QuickScanEngine;` appears to solve the issue:
```perl
use strict;
use FindBin;
use lib $FindBin::Bin;
use QuickScanEngine;
```
Not sure how good of a solution is (is the FindBin package installed with perl by default?). I am gonna make a little research and be back with a PR if this seems a good solution.
